export default [
	{
		title: '風のクロノア2 ～世界が望んだ忘れもの～',
		category: 'Any% Popkaless',
		runnerPkAry: [0, 1],
		commentatorPkAry: [69],
		duration: '01:50:00',
		pk: 20,
	},
	{
		title: 'スプラトゥーン2',
		category: 'Any%',
		runnerPkAry: [2],
		commentatorPkAry: [],
		duration: '01:50:00',
		pk: 5,
	},
	{
		title: 'Dr. Luigi',
		category: 'Lカプセル 0-20LV（MED）',
		runnerPkAry: [3],
		commentatorPkAry: [],
		duration: '00:15:00',
		pk: 40,
	},
	{
		title: '流星のロックマン2',
		category: 'Any% Cards',
		runnerPkAry: [4],
		commentatorPkAry: [80],
		duration: '02:10:00',
		pk: 27,
	},
	{
		title: 'ポケットモンスター金/銀',
		category: 'Any% Glitchless レッド撃破',
		runnerPkAry: [5],
		commentatorPkAry: [80],
		duration: '03:27:00',
		pk: 39,
	},
	{
		title: 'Hearthstone',
		category: 'Heroic Karazhan',
		runnerPkAry: [6, 7],
		commentatorPkAry: [88],
		duration: '01:30:00',
		pk: 32,
	},
	{
		title: 'バイオハザード4',
		category: 'New Game＋Any%',
		runnerPkAry: [8],
		commentatorPkAry: [],
		duration: '01:30:00',
		pk: 22,
	},
	{
		title: 'セットアップブロック 1',
		category: '',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '01:00:00',
		pk: -1,
	},
	{
		title: 'イース・オリジン',
		category: 'Any% (Yunica)',
		runnerPkAry: [9],
		commentatorPkAry: [78],
		duration: '01:45:00',
		pk: 37,
	},
	{
		title: '星のカービィスーパーデラックス',
		category: '100%',
		runnerPkAry: [10],
		commentatorPkAry: [91],
		duration: '01:20:00',
		pk: 53,
	},
	{
		title: 'スターオーシャン',
		category: 'Any%',
		runnerPkAry: [11],
		commentatorPkAry: [86],
		duration: '03:05:00',
		pk: 9,
	},
	{
		title: 'スーパーマリオブラザーズ',
		category: 'Warpless',
		runnerPkAry: [12],
		commentatorPkAry: [44],
		duration: '00:23:00',
		pk: 38,
	},
	{
		title: 'スーパーマリオブラザーズ3',
		category: '100%',
		runnerPkAry: [13],
		commentatorPkAry: [],
		duration: '01:20:00',
		pk: 51,
	},
	{
		title: 'スーパーマリオ64',
		category: 'Any% – 2 players 1 controller',
		runnerPkAry: [14],
		commentatorPkAry: [87],
		duration: '00:30:00',
		pk: 1,
	},
	{
		title: 'ゼルダの伝説 時のオカリナ',
		category: 'Reverse Dungeon Order',
		runnerPkAry: [15, 16],
		commentatorPkAry: [73],
		duration: '02:05:00',
		pk: 50,
	},
	{
		title: 'ゼルダの伝説 夢をみる島DX',
		category: 'Any% No WW/OOB',
		runnerPkAry: [17, 18],
		commentatorPkAry: [],
		duration: '01:00:00',
		pk: 49,
	},
	{
		title: 'スーパードンキーコングシリーズ１，２，３ トリロジーリレー',
		category: '',
		runnerPkAry: [19, 20, 21],
		commentatorPkAry: [],
		duration: '02:30:00',
		pk: 16,
	},
	{
		title: 'ドラえもん',
		category: 'Any%',
		runnerPkAry: [22],
		commentatorPkAry: [],
		duration: '00:20:00',
		pk: 33,
	},
	{
		title: 'ブラストドーザー',
		category: 'Any%(JP)',
		runnerPkAry: [23],
		commentatorPkAry: [82],
		duration: '00:30:00',
		pk: 12,
	},
	{
		title: 'ファイアーエムブレム トラキア７７６',
		category: 'Any%',
		runnerPkAry: [24],
		commentatorPkAry: [76],
		duration: '02:20:00',
		pk: 52,
	},
	{
		title: 'ワンダープロジェクトJ 機械の少年ピーノ',
		category: 'Any%',
		runnerPkAry: [25],
		commentatorPkAry: [70],
		duration: '02:30:00',
		pk: 24,
	},
	{
		title: 'セットアップブロック 2',
		category: '',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '01:00:00',
		pk: -1,
	},
	{
		title: 'Lightning Returns Final Fantasy XIII',
		category: 'Normal Any%',
		runnerPkAry: [26],
		commentatorPkAry: [],
		duration: '02:20:00',
		pk: 19,
	},
	{
		title: 'がんばれゴエモン2 奇天烈将軍マッギネス',
		category: 'Any%',
		runnerPkAry: [27],
		commentatorPkAry: [],
		duration: '00:45:00',
		pk: 29,
	},
	{
		title: 'がんばれゴエモン〜でろでろ道中 オバケてんこ盛り〜',
		category: 'Any% CO-OP',
		runnerPkAry: [28],
		commentatorPkAry: [27],
		duration: '01:55:00',
		pk: 46,
	},
	{
		title: 'ルイージマンション',
		category: 'Any% (No OoB)',
		runnerPkAry: [29],
		commentatorPkAry: [],
		duration: '01:05:00',
		pk: 43,
	},
	{
		title: 'アンリミテッドサガ',
		category: 'ローラ編',
		runnerPkAry: [30, 31],
		commentatorPkAry: [72],
		duration: '02:10:00',
		pk: 35,
	},
	{
		title: 'GOD HAND',
		category: 'HARD NewGame',
		runnerPkAry: [32],
		commentatorPkAry: [],
		duration: '02:00:00',
		pk: 42,
	},
	{
		title: 'ドンキーコング64',
		category: 'Any%',
		runnerPkAry: [33],
		commentatorPkAry: [34],
		duration: '00:32:00',
		pk: 15,
	},
	{
		title: '64で発見!!たまごっち みんなでたまごっちワールド',
		category: 'Any%',
		runnerPkAry: [34],
		commentatorPkAry: [71],
		duration: '00:40:00',
		pk: 34,
	},
	{
		title: 'スーパーマリオUSA',
		category: 'Warpless',
		runnerPkAry: [35, 36],
		commentatorPkAry: [74],
		duration: '00:30:00',
		pk: 18,
	},
	{
		title: 'ゼルダの伝説 ムジュラの仮面3D',
		category: 'Any%',
		runnerPkAry: [37],
		commentatorPkAry: [81],
		duration: '01:35:00',
		pk: 21,
	},
	{
		title: 'ゼルダの伝説 時のオカリナ',
		category: 'No IM/WW',
		runnerPkAry: [38, 39],
		commentatorPkAry: [16],
		duration: '01:28:00',
		pk: 41,
	},
	{
		title: 'ロックマン2',
		category: 'Any％ 壁抜けあり',
		runnerPkAry: [40],
		commentatorPkAry: [83],
		duration: '00:35:00',
		pk: 31,
	},
	{
		title: 'Twitch Plays Crypt of the NecroDancer: AMPLIFIED Zone 1 Bard',
		category: '',
		runnerPkAry: [41],
		commentatorPkAry: [],
		duration: '00:30:00',
		pk: 47,
	},
	{
		title: '半熟英雄',
		category: 'any% ALLクリア(シナリオ123を連続でクリア) 卵回復なし',
		runnerPkAry: [42],
		commentatorPkAry: [],
		duration: '01:30:00',
		pk: 28,
	},
	{
		title: 'Enter the Gungeon',
		category: '4 Character Speedrun',
		runnerPkAry: [43],
		commentatorPkAry: [],
		duration: '01:40:00',
		pk: 25,
	},
	{
		title: 'チャレンジャー',
		category: 'Any%',
		runnerPkAry: [44],
		commentatorPkAry: [],
		duration: '00:15:00',
		pk: 11,
	},
	{
		title: 'セットアップブロック 3',
		category: '',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '01:00:00',
		pk: -1,
	},
	{
		title: 'Final Fantasy XII International Zodiac Job System',
		category: 'Any%',
		runnerPkAry: [45],
		commentatorPkAry: [],
		duration: '04:00:00',
		pk: 8,
	},
	{
		title: '星のカービィWii',
		category: 'Any%',
		runnerPkAry: [46],
		commentatorPkAry: [],
		duration: '01:45:00',
		pk: 45,
	},
	{
		title: '実況パワフルプロ野球8',
		category: 'ドラフ島編(セントラルタワールート)',
		runnerPkAry: [47, 48],
		commentatorPkAry: [89],
		duration: '00:45:00',
		pk: 30,
	},
	{
		title:
			'美味しんぼ 究極のメニュー三本勝負シングルエリミネーショントーナメント',
		category: '',
		runnerPkAry: [49],
		commentatorPkAry: [],
		duration: '00:45:00',
		pk: 48,
	},
	{
		title: 'デモンズソウル',
		category: 'Any% Glitchless',
		runnerPkAry: [50],
		commentatorPkAry: [],
		duration: '01:00:00',
		pk: 17,
	},
	{
		title: 'ドラゴンクエスト5',
		category: 'Any% Glitchless (カジノ技使用)',
		runnerPkAry: [51],
		commentatorPkAry: [85],
		duration: '06:10:00',
		pk: 14,
	},
	{
		title: 'Tetris: The Grand Master series(TGM1・2・3)',
		category: '',
		runnerPkAry: [],
		commentatorPkAry: [90],
		duration: '01:25:00',
		pk: 10,
	},
	{
		title: 'テトリス with カードキャプターさくら エターナルハート',
		category: 'Story Mode (Normal)',
		runnerPkAry: [55, 57],
		commentatorPkAry: [84],
		duration: '00:25:00',
		pk: 7,
	},
	{
		title: 'テトリスDX',
		category: '40LINES',
		runnerPkAry: [55],
		commentatorPkAry: [],
		duration: '00:05:00',
		pk: 6,
	},
	{
		title: 'Sa・ga2秘宝伝説',
		category: 'Any%(毒バグ有)',
		runnerPkAry: [58],
		commentatorPkAry: [],
		duration: '00:10:00',
		pk: 36,
	},
	{
		title: 'ラチェット&クランク2 ガガガ!銀河のコマンドーっす',
		category: 'Any%',
		runnerPkAry: [59],
		commentatorPkAry: [75],
		duration: '01:20:00',
		pk: 0,
	},
	{
		title: 'ファイアーエムブレム 紋章の謎 第１部暗黒竜と光の剣',
		category: '全員生存ファルシオン取得チャート',
		runnerPkAry: [60],
		commentatorPkAry: [],
		duration: '02:50:00',
		pk: 54,
	},
	{
		title: '実況パワフルプロ野球2012',
		category: 'パワフルナイン',
		runnerPkAry: [61],
		commentatorPkAry: [],
		duration: '02:00:00',
		pk: 23,
	},
	{
		title: 'セットアップブロック 4',
		category: '',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '01:00:00',
		pk: -1,
	},
	{
		title: 'オプーナ',
		category: 'Any%',
		runnerPkAry: [62],
		commentatorPkAry: [77],
		duration: '05:00:00',
		pk: 4,
	},
	{
		title: 'ポケモン不思議のダンジョン青の救助隊',
		category: 'Any% Save+Quit',
		runnerPkAry: [63],
		commentatorPkAry: [],
		duration: '02:05:00',
		pk: 26,
	},
	{
		title: 'ぷよぷよSUN',
		category: 'All Mode – Normal',
		runnerPkAry: [64],
		commentatorPkAry: [],
		duration: '00:25:00',
		pk: 44,
	},
	{
		title: 'Child of Light',
		category: '100%',
		runnerPkAry: [65],
		commentatorPkAry: [],
		duration: '01:50:00',
		pk: 3,
	},
	{
		title: '火の鳥 鳳凰編 我王の冒険',
		category: 'Any%',
		runnerPkAry: [66, 67],
		commentatorPkAry: [],
		duration: '00:20:00',
		pk: 13,
	},
	{
		title: 'スーパーマリオワールド',
		category: '96 Exits(100%)',
		runnerPkAry: [68],
		commentatorPkAry: [],
		duration: '01:30:00',
		pk: 2,
	},
];
