export default [
	{
		title: 'Bloodstained: Curse of the Moon',
		category: 'Zangetsu Only Normal Veteran',
		runnerPkAry: [91, 9],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 0,
	},
	{
		title: 'ゼルダの伝説 トワイライトプリンセスHD',
		category: 'Any%',
		runnerPkAry: [25],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 1,
	},
	{
		title: 'ゼルダの伝説 風のタクトHD',
		category: 'Any%',
		runnerPkAry: [50],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 2,
	},
	{
		title: 'Life is Strange',
		category: 'Episode 1: Chrysalis Any%',
		runnerPkAry: [48],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 3,
	},
	{
		title: 'サンドラの大冒険',
		category: 'Any%',
		runnerPkAry: [137],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 4,
	},
	{
		title: 'ソニックアドベンチャーDX',
		category: "Sonic's Story",
		runnerPkAry: [77],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 5,
	},
	{
		title: 'ロックマンX8',
		category: 'Any%',
		runnerPkAry: [87],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 6,
	},
	{
		title: 'シャドウハーツ フロム・ザ・ニューワールド',
		category: 'Any%',
		runnerPkAry: [107],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 7,
	},
	{
		title: 'ルーンファクトリー フロンティア',
		category: 'Any%',
		runnerPkAry: [140],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 8,
	},
	{
		title: '電脳戦機バーチャロンマーズ',
		category: 'New Game',
		runnerPkAry: [24],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 9,
	},
	{
		title: 'セットアップタイム1',
		runnerPkAry: [],
		commentatorPkAry: [],
		pk: 10,
	},
	{
		title: '魔導物語はなまる大幼稚園児',
		category: 'Any%',
		runnerPkAry: [76],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 11,
	},
	{
		title: 'STAR OCEAN SECOND EVOLUTION',
		category: 'Any%',
		runnerPkAry: [127],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 12,
	},
	{
		title: 'ラチェット＆クランク',
		category: 'Any%',
		runnerPkAry: [130],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 13,
	},
	{
		title: 'パネルでポン',
		category: 'VS COM EASY - S-HARD',
		runnerPkAry: [68],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 14,
	},
	{
		title: 'Wii Party',
		category: 'Solo Mode-Beginner',
		runnerPkAry: [58],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 15,
	},
	{
		title: 'Wii Party',
		category: '4 Player Minigames Tropical Punch',
		runnerPkAry: [58],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 16,
	},
	{
		title: 'ドンキーコングジャングルビート',
		category: 'Any% Cactus King',
		runnerPkAry: [96],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 17,
	},
	{
		title: 'ドラゴンボールZ 超サイヤ伝説',
		category: 'Rader%(バグ有りAny%)',
		runnerPkAry: [96],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 18,
	},
	{
		title: '悪魔城ドラキュラ Xクロニクル',
		category: 'One Character Only - Maria',
		runnerPkAry: [28],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 19,
	},
	{
		title: 'マイティボンジャック',
		category: '爆弾ワープ無し・真エンディング',
		runnerPkAry: [106],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 20,
	},
	{
		title: '邪聖剣ネクロマンサー',
		category: 'Any%(宝箱バグ利用)',
		runnerPkAry: [93],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 21,
	},
	{
		title: '麻雀ウォーズ',
		category: 'Any% 名前バグ（ももよバグ）利用',
		runnerPkAry: [93],
		commentatorPkAry: [],
		duration: '0:05:00',
		pk: 22,
	},
	{
		title: '閃乱カグラ Estival Versus',
		category: 'New Game Any%',
		runnerPkAry: [23, 35],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 23,
	},
	{
		title: 'モンスターファーム2',
		category: 'Beat the Legend Cup',
		runnerPkAry: [38],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 24,
	},
	{
		title: 'セットアップタイム2',
		runnerPkAry: [],
		commentatorPkAry: [],
		pk: 25,
	},
	{
		title: 'Getting Over It With Bennett Foddy',
		category: 'Glitchless',
		runnerPkAry: [2],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 26,
	},
	{
		title: 'ACE OF SEAFOOD',
		category: 'All Reefs',
		runnerPkAry: [32],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 27,
	},
	{
		title: '野生動物のレース',
		category: 'All Cups',
		runnerPkAry: [71],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 28,
	},
	{
		title: 'くまのプーさんのホームランダービー！',
		category: 'オールクリア（ロビン打倒）',
		runnerPkAry: [20, 134],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 29,
	},
	{
		title: '時と永遠～トキトワ～',
		category: 'Any%',
		runnerPkAry: [109],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 30,
	},
	{
		title: 'Minit',
		category: 'Normal Any%',
		runnerPkAry: [31],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 31,
	},
	{
		title: 'Undertale',
		category: 'TPE Glitchless',
		runnerPkAry: [45],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 32,
	},
	{
		title: 'ハローキティのピコピコ大作戦！',
		category: 'Any%',
		runnerPkAry: [80],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 33,
	},
	{
		title: '15m challenge tournament',
		category: '',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 34,
	},
	{
		title: '風のクロノア: door to phantomile',
		category: 'Any%',
		runnerPkAry: [44, 94],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 35,
	},
	{
		title: 'キャッスルヴァニア 白夜の協奏曲 マクシームレースリレー',
		category: 'Any%',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 36,
	},
	{
		title: 'ドラえもん２ のび太のトイズランド大冒険',
		category: 'Any%',
		runnerPkAry: [110],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 37,
	},
	{
		title: 'スーパーマリオオデッセイ',
		category: 'Any%',
		runnerPkAry: [56],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 38,
	},
	{
		title: 'チョロQHG2',
		category: 'Any%',
		runnerPkAry: [128],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 39,
	},
	{
		title: 'がんばれゴエモン〜宇宙海賊アコギング〜',
		category: 'Any%',
		runnerPkAry: [117],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 40,
	},
	{
		title: 'カトちゃんケンちゃん',
		category: 'Any% Warps',
		runnerPkAry: [41],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 41,
	},
	{
		title: 'ドンドコドン2',
		category: 'Any%',
		runnerPkAry: [69],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 42,
	},
	{
		title: '鋼-HAGANE-',
		category: 'Any%',
		runnerPkAry: [22, 29],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 43,
	},
	{
		title: 'セットアップタイム3',
		runnerPkAry: [],
		commentatorPkAry: [],
		pk: 44,
	},
	{
		title: '世界樹の迷宮',
		category: 'Any%',
		runnerPkAry: [74],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 45,
	},
	{
		title: 'エッグマニア つかんで！まわして！どっすんぱず～る！！',
		category: 'Hard boiled hard',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 46,
	},
	{
		title: '星のカービィ 夢の泉の物語',
		category: 'Any% No Major Glitches',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 47,
	},
	{
		title: '星のカービィ3',
		category: 'Any% - 2P',
		runnerPkAry: [119],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 48,
	},
	{
		title: '「心の中の3号」撃破トーナメント',
		category: '',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 49,
	},
	{
		title: 'Monster Hunter:World',
		category: 'Any% Colossal Task',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 50,
	},
	{
		title: '聖剣伝説２',
		category: '1 player 2 controller',
		runnerPkAry: [54],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 51,
	},
	{
		title: 'ポケットモンスター ダイヤモンド・パール',
		category: 'Any% Glichted',
		runnerPkAry: [90],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 52,
	},
	{
		title: 'スーパーマリオ ヨッシーアイランド',
		category: '100%',
		runnerPkAry: [101],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 53,
	},
	{
		title: 'スーパーマリオ ヨッシーアイランド',
		category: 'Any% Credits Warp',
		runnerPkAry: [101],
		commentatorPkAry: [],
		duration: '0:05:00',
		pk: 54,
	},
	{
		title: '最強羽生将棋',
		category: 'Any%',
		runnerPkAry: [143],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 55,
	},
	{
		title: '本将棋 内藤九段将棋秘伝シングルエリミネーショントーナメント',
		category: 'Any%',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 56,
	},
	{
		title: 'ボンバーマンファンタジーレース',
		category: 'Any%(Normal Courses)',
		runnerPkAry: [47],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 57,
	},
	{
		title: 'スーパーボンバーマン３',
		category: 'Any%',
		runnerPkAry: [125],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 58,
	},
	{
		title: 'ワリオランド3 不思議なオルゴール',
		category: 'Any% Glitchless',
		runnerPkAry: [84],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 59,
	},
	{
		title: '伝説のスタフィー',
		category: 'Any% Glitchless',
		runnerPkAry: [83, 83, 115],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 60,
	},
	{
		title: 'ドラゴンクエスト2',
		category: 'Normal Ending',
		runnerPkAry: [36],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 61,
	},
	{
		title: 'セットアップタイム4',
		runnerPkAry: [],
		commentatorPkAry: [],
		pk: 62,
	},
	{
		title: '黒い瞳のノア',
		category: 'Any%',
		runnerPkAry: [113, 59],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 63,
	},
	{
		title: '時空の覇者 Sa・Ga3 ［完結編］',
		category: 'Any%',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 64,
	},
	{
		title: 'ポケットモンスター ダイヤモンド・パール',
		category: 'Any% Glitchless',
		runnerPkAry: [90],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 65,
	},
	{
		title: 'ポケモンスナップ',
		category: '250k Points',
		runnerPkAry: [19],
		commentatorPkAry: [],
		duration: '0:10:00',
		pk: 66,
	},
	{
		title: 'スーパードンキーコングシリーズ1,2,3完全クリアトリロジーリレー',
		category: '完全クリア',
		runnerPkAry: [],
		commentatorPkAry: [],
		duration: '0:15:00',
		pk: 67,
	},
];
