export default [
	{
		pk: 1,
		name: '）',
		twitch: 'r_parenthesis',
		nico: 'co1535557',
		twitter: 'r_parenthesis',
	},
	{pk: 2, name: 'Amount', twitch: '', nico: 'co3611145', twitter: 'amount_w'},
	{pk: 3, name: 'ASURA', twitch: '', nico: 'co3095414', twitter: 'ASURA398'},
	{
		pk: 4,
		name: 'box',
		twitch: 'box10000',
		nico: 'co39427',
		twitter: 'box10000',
	},
	{
		pk: 5,
		name: 'Cabbage',
		twitch: '891cabbage',
		nico: 'co2799457',
		twitter: '891cabbage',
	},
	{
		pk: 6,
		name: 'caeshura',
		twitch: 'caeshura',
		nico: '',
		twitter: 'CaeshuraL',
	},
	{
		pk: 7,
		name: 'Cma',
		twitch: 'cma2819',
		nico: 'co1690439',
		twitter: 'cma2819',
	},
	{pk: 8, name: 'Crocus', twitch: '', nico: '', twitter: ''},
	{
		pk: 9,
		name: 'FU2(ふつ)',
		twitch: 'fu2_2525',
		nico: 'co91083',
		twitter: 'fu2_2525',
	},
	{
		pk: 10,
		name: 'gameO',
		twitch: 'gameopoona',
		nico: '',
		twitter: 'gameopoona',
	},
	{
		pk: 11,
		name: 'GANSEK1',
		twitch: 'gansek1',
		nico: '',
		twitter: 'toshi72991',
	},
	{
		pk: 12,
		name: 'hashedrice',
		twitch: 'hashedrice',
		nico: '',
		twitter: 'hashedrice8',
	},
	{
		pk: 13,
		name: 'hebo-MAI',
		twitch: 'hebo_MAI',
		nico: 'co209209',
		twitter: 'hebo_MAI',
	},
	{
		pk: 14,
		name: 'HiST',
		twitch: 'hist1889',
		nico: 'co473223',
		twitter: 'hukujunn',
	},
	{
		pk: 15,
		name: 'horand',
		twitch: 'horand2525',
		nico: 'co1852756',
		twitter: 'horand3875',
	},
	{
		pk: 16,
		name: 'KABI',
		twitch: 'kabiranran',
		nico: '',
		twitter: 'KABIranran',
	},
	{
		pk: 17,
		name: 'KANNO',
		twitch: 'KANONN64',
		nico: 'co3568531',
		twitter: 'KANNON64mario',
	},
	{
		pk: 18,
		name: 'kazoo',
		twitch: 'kazookun',
		nico: 'co255011',
		twitter: 'kazoosgame',
	},
	{
		pk: 19,
		name: 'Koto（こと）',
		twitch: '',
		nico: 'co2722221',
		twitter: 'koto_0219',
	},
	{pk: 20, name: 'last', twitch: '', nico: '', twitter: 'last_794780'},
	{
		pk: 21,
		name: 'lawren',
		twitch: 'lawren0519',
		nico: 'co2513144',
		twitter: 'lawren0519',
	},
	{pk: 22, name: 'LK', twitch: 'lk_431', nico: '', twitter: 'LK_431'},
	{pk: 23, name: 'lz', twitch: 'mdr_lz', nico: '', twitter: 'dkc1mldz9r'},
	{pk: 24, name: 'Naka', twitch: 'keyn_naka', nico: '', twitter: ''},
	{pk: 25, name: 'Nekroz', twitch: '', nico: '', twitter: 'Nekroz0316'},
	{pk: 26, name: 'neploli', twitch: 'neploli', nico: '', twitter: 'neploli'},
	{
		pk: 27,
		name: 'nezumii',
		twitch: 'nezumiirta',
		nico: 'co2038254',
		twitter: 'nezumii2',
	},
	{
		pk: 28,
		name: 'NOVel',
		twitch: 'NOVel_RTA',
		nico: '',
		twitter: 'NOVel_RTA',
	},
	{pk: 29, name: 'ohon', twitch: 'ohonta', nico: '', twitter: 'ohonhbkp'},
	{
		pk: 30,
		name: 'ryota',
		twitch: 'ryota0623',
		nico: 'co3861713',
		twitter: 'syuzo1106',
	},
	{
		pk: 31,
		name: 'sasasa',
		twitch: 'sasasa0404',
		nico: '',
		twitter: 'sasasa0701',
	},
	{
		pk: 32,
		name: 'seri',
		twitch: 'seri17723',
		nico: '',
		twitter: 'serika_parle',
	},
	{
		pk: 33,
		name: 'signakong',
		twitch: 'signakong',
		nico: '',
		twitter: 'signakong',
	},
	{pk: 34, name: 'Su', twitch: '', nico: 'co3851568', twitter: 'cstrakm'},
	{pk: 35, name: 'Suzuri', twitch: 'suzuri42', nico: '', twitter: 'nadu7793'},
	{
		pk: 36,
		name: 'twitchpop',
		twitch: 'twitchpoppop',
		nico: '',
		twitter: 'pop_twitch',
	},
	{pk: 37, name: 'vaxherd', twitch: 'vaxherd', nico: '', twitter: ''},
	{
		pk: 38,
		name: 'y_gm',
		twitch: 'y_gm',
		nico: 'co1248079',
		twitter: 'yagamuu',
	},
	{
		pk: 39,
		name: 'Yagamoth',
		twitch: 'Yagamoth',
		nico: '',
		twitter: 'DonYagamoth',
	},
	{
		pk: 40,
		name: 'yamayuu',
		twitch: 'yamayuu1223',
		nico: 'co3507639',
		twitter: 'yamayuu1223',
	},
	{pk: 41, name: 'Zzz', twitch: 'zzz_pc', nico: '', twitter: 'Zzz_pc'},
	{
		pk: 42,
		name: 'アカナ',
		twitch: 'akana_aa',
		nico: 'co624559',
		twitter: 'batan168',
	},
	{
		pk: 43,
		name: 'あきす',
		twitch: 'akisu_nico',
		nico: 'co1852549',
		twitter: 'akisu_nico',
	},
	{pk: 44, name: 'あぐね', twitch: 'agne567', nico: '', twitter: 'agne567'},
	{pk: 45, name: 'アシラム', twitch: '', nico: '', twitter: 'asiraM_6053'},
	{pk: 46, name: 'あすなろ', twitch: '', nico: '', twitter: 'thujopsis622'},
	{
		pk: 47,
		name: 'ありちゃん',
		twitch: 'bofaric',
		nico: 'co3643749',
		twitter: 'bofaric',
	},
	{
		pk: 48,
		name: 'あるてん',
		twitch: 'arten0104',
		nico: 'co3467849',
		twitter: 'arten0104',
	},
	{
		pk: 49,
		name: 'イトタカ',
		twitch: 'itotaka1031',
		nico: 'co1399871',
		twitter: 'itotaka1031_119',
	},
	{
		pk: 50,
		name: 'いわび',
		twitch: 'iwabi74',
		nico: 'co2807239',
		twitter: 'iwabi74',
	},
	{
		pk: 51,
		name: 'うしゅ～',
		twitch: 'usyuuu',
		nico: 'co3601066',
		twitter: 'usyuuuuu',
	},
	{
		pk: 52,
		name: 'うめだJAPAN',
		twitch: 'umedajapan',
		nico: '',
		twitter: 'umesooooo',
	},
	{
		pk: 53,
		name: 'かいざあ',
		twitch: 'caiser_',
		nico: 'co3478568',
		twitter: 'caiser__',
	},
	{pk: 54, name: 'かいわれ', twitch: '', nico: '', twitter: 'temo1222'},
	{
		pk: 55,
		name: 'カナタ',
		twitch: 'at_kanata64',
		nico: 'co3102225',
		twitter: 'at_kanata',
	},
	{
		pk: 56,
		name: 'かにかま',
		twitch: 'kanikama100',
		nico: 'co3575050',
		twitter: 'kaitoushite',
	},
	{
		pk: 57,
		name: 'ガンジョンおじさん',
		twitch: 'etg_ojsn',
		nico: '',
		twitter: 'EtG_ojsn',
	},
	{
		pk: 58,
		name: 'かんちょつ',
		twitch: 'kanchots',
		nico: 'co3779756',
		twitter: 'kanchots',
	},
	{
		pk: 59,
		name: 'くろぷす',
		twitch: 'clowps',
		nico: 'co356655',
		twitter: 'cl_op_s',
	},
	{
		pk: 60,
		name: 'ぐんそう±',
		twitch: 'gunsou_pl_mi',
		nico: '',
		twitter: 'gunsou_pl_mi',
	},
	{
		pk: 61,
		name: 'げきから',
		twitch: 'gekikara_vins',
		nico: '',
		twitter: 'gekikara_vins',
	},
	{
		pk: 62,
		name: 'サケノミ',
		twitch: 'sakenomi3',
		nico: 'co3235710',
		twitter: 'huhihi2525',
	},
	{
		pk: 63,
		name: 'ざにゃあ',
		twitch: 'zanyaa_iki',
		nico: 'co2054943',
		twitter: 'zanyaa2525',
	},
	{pk: 64, name: 'さばと', twitch: '', nico: '', twitter: 'kizamix'},
	{
		pk: 65,
		name: 'サボてん',
		twitch: 'savoteen',
		nico: 'co2228036',
		twitter: 'savo_ten',
	},
	{
		pk: 66,
		name: 'しぇん',
		twitch: 'shien_OG',
		nico: '',
		twitter: 'shien_peer',
	},
	{
		pk: 67,
		name: 'シャーフ',
		twitch: 'w_sy_f',
		nico: 'co1745475',
		twitter: 'weisses_schaf',
	},
	{
		pk: 68,
		name: 'しゅが',
		twitch: 'syuga218',
		nico: 'co1645336',
		twitter: 'syuga_sm',
	},
	{
		pk: 69,
		name: 'しょか',
		twitch: 'shokashoka',
		nico: 'co72337',
		twitter: 'shokashoka',
	},
	{pk: 70, name: 'すする', twitch: 'susuru_3', nico: 'co625640', twitter: ''},
	{
		pk: 71,
		name: 'スピンス',
		twitch: '@spins72',
		nico: 'co2494841',
		twitter: 'spins72',
	},
	{
		pk: 72,
		name: 'せーら',
		twitch: 'sera18171',
		nico: 'co2105438',
		twitter: 'sera18171',
	},
	{
		pk: 73,
		name: 'せろり',
		twitch: 'celery_jpn',
		nico: 'co3668387',
		twitter: 'serori224',
	},
	{
		pk: 74,
		name: 'そらー',
		twitch: 'sora_999',
		nico: 'co2808990',
		twitter: 'sora_soramame99',
	},
	{pk: 75, name: 'たんせい', twitch: 'tansei29', nico: '', twitter: ''},
	{pk: 76, name: 'ちーな', twitch: '', nico: 'co1952595', twitter: 'tiina_y'},
	{
		pk: 77,
		name: 'チェスト',
		twitch: 'chestchestjp',
		nico: 'co3835827',
		twitter: 'chestchestjp',
	},
	{
		pk: 78,
		name: 'チョチョキリモイス',
		twitch: '',
		nico: '4552280',
		twitter: 'cyocyokirimoice',
	},
	{
		pk: 79,
		name: 'トーボウ',
		twitch: 'toobou',
		nico: 'co260847',
		twitter: 'toobou',
	},
	{
		pk: 80,
		name: 'とよまな',
		twitch: 'toyomana',
		nico: '',
		twitter: 'ToyoMana64',
	},
	{
		pk: 81,
		name: 'とらっしー',
		twitch: 'tiger_twittch',
		nico: 'co1337373',
		twitter: 'tiger1atan1nabe?lang=ja',
	},
	{
		pk: 82,
		name: 'なぜだ！',
		twitch: 'nazeda777',
		nico: 'co3215154',
		twitter: 'nazeda777',
	},
	{pk: 83, name: 'なたげ', twitch: 'hitodena', nico: '', twitter: 'hitodena'},
	{pk: 84, name: 'ねぐるしい', twitch: 'negurusii', nico: '', twitter: ''},
	{
		pk: 85,
		name: 'ねこ',
		twitch: 'neko_22',
		nico: 'co3364893',
		twitter: 'ckit_22',
	},
	{
		pk: 86,
		name: 'ネッピー',
		twitch: 'neppie_peer',
		nico: '',
		twitter: 'neppie_peer',
	},
	{pk: 87, name: 'のんのん', twitch: '', nico: '', twitter: 'nonnonx8'},
	{pk: 88, name: 'バカンダ', twitch: '', nico: '', twitter: 'bakanda_peer'},
	{
		pk: 89,
		name: 'ばくぜろ',
		twitch: 'baku_zero',
		nico: 'co1236759',
		twitter: 'baku_zero',
	},
	{
		pk: 90,
		name: 'ばすたぁ',
		twitch: 'buster_poke',
		nico: 'co1888777',
		twitter: 'Buster_poke',
	},
	{
		pk: 91,
		name: 'はなげ',
		twitch: 'hanage_belmondo',
		nico: 'co72738',
		twitter: 'hanage2525',
	},
	{
		pk: 92,
		name: 'はるかぜ',
		twitch: '',
		nico: 'co1195140',
		twitter: 'Etarnal_wind',
	},
	{
		pk: 93,
		name: 'はるく',
		twitch: 'radio613',
		nico: 'co1846965',
		twitter: 'radio613',
	},
	{
		pk: 94,
		name: 'はるとも / Harutomo',
		twitch: 'harutomo',
		nico: '',
		twitter: 'harut0mo',
	},
	{
		pk: 95,
		name: 'バン',
		twitch: 'bann_jpn',
		nico: 'co3219615',
		twitter: 'suugaku2b?lang=ja',
	},
	{
		pk: 96,
		name: 'ふぃす',
		twitch: 'fis0324',
		nico: 'co16969',
		twitter: 'fis314',
	},
	{
		pk: 97,
		name: 'プニュタ',
		twitch: 'punyuta',
		nico: 'co2272646',
		twitter: 'punyuta__rta',
	},
	{pk: 98, name: 'ブレーキ', twitch: 'brakemg', nico: '', twitter: 'brakeMg'},
	{
		pk: 99,
		name: 'べべーん',
		twitch: 'be_be_be_',
		nico: 'co1364491',
		twitter: 'be_be_be_',
	},
	{
		pk: 100,
		name: 'へるまん',
		twitch: 'after_5_star',
		nico: '',
		twitter: 'After_5_Star',
	},
	{
		pk: 101,
		name: 'ぽぉ',
		twitch: 'poahr',
		nico: '',
		twitter: 'PoahrYoshiGod',
	},
	{
		pk: 102,
		name: 'まいば',
		twitch: 'maiba0921',
		nico: 'co3803194',
		twitter: 'maibaRTA',
	},
	{
		pk: 103,
		name: 'まさご',
		twitch: 'masagon53',
		nico: 'co150542',
		twitter: 'masago53',
	},
	{pk: 104, name: 'みがさかＡ', twitch: '', nico: '', twitter: 'Migasaka'},
	{
		pk: 105,
		name: 'ミクロン',
		twitch: 'mikurom12',
		nico: 'co3384797',
		twitter: 'mikurom12',
	},
	{
		pk: 106,
		name: 'みすめさん',
		twitch: '',
		nico: 'co120764',
		twitter: 'msm_smtn',
	},
	{
		pk: 107,
		name: 'ミッド',
		twitch: 'mid_kun',
		nico: 'co2835300',
		twitter: 'mid_luigi',
	},
	{
		pk: 108,
		name: 'みとん',
		twitch: 'miton3t',
		nico: 'co2323506/38474273',
		twitter: 'mittonton10',
	},
	{pk: 109, name: 'もか', twitch: 'mokapeer', nico: '', twitter: 'moka_peer'},
	{
		pk: 110,
		name: 'モグ',
		twitch: 'mog_stream',
		nico: 'co3361245',
		twitter: 'mogrta1',
	},
	{
		pk: 111,
		name: 'もす',
		twitch: 'mosstkm',
		nico: 'co2772190',
		twitter: 'Creeping_LUIGI',
	},
	{
		pk: 112,
		name: 'もちごめ',
		twitch: 'mochigome2525',
		nico: 'co1849514',
		twitter: 'mcgm_m31',
	},
	{
		pk: 113,
		name: 'もっち',
		twitch: 'ym10000',
		nico: 'co222824',
		twitter: 'LP65535',
	},
	{pk: 114, name: 'もぶ', twitch: 'mobu_ngo', nico: '', twitter: 'mobu_ngo'},
	{
		pk: 115,
		name: 'ゆーでー',
		twitch: 'agdf_ydy',
		nico: '',
		twitter: 'agdf_ydy',
	},
	{
		pk: 116,
		name: 'ゆとりん',
		twitch: 'mechayutori',
		nico: '',
		twitter: 'M_YTR_FRMK',
	},
	{
		pk: 117,
		name: 'ラヴィ',
		twitch: 'ravi_hina0303',
		nico: '',
		twitter: 'hinatan_ravi',
	},
	{
		pk: 118,
		name: 'ラッコせんせ。',
		twitch: 'rakkosense',
		nico: 'co1718878',
		twitter: 'rakkosense',
	},
	{
		pk: 119,
		name: 'りぷて',
		twitch: 'pletty7',
		nico: 'co103204',
		twitter: 'lpt_voltecker',
	},
	{
		pk: 120,
		name: 'リョーマ',
		twitch: 'ryoma2744',
		nico: 'co3810352',
		twitter: 'ryoma2744',
	},
	{
		pk: 121,
		name: 'りょくちゃ',
		twitch: 'suitougreentea',
		nico: '',
		twitter: 'suitougreentea',
	},
	{
		pk: 122,
		name: 'るなそる',
		twitch: 'runasoru',
		nico: '39528808',
		twitter: 'runasoru',
	},
	{
		pk: 123,
		name: 'ロロット',
		twitch: 'rorotto',
		nico: 'co1426770',
		twitter: 'rorotto__',
	},
	{
		pk: 124,
		name: '鍵村キィ',
		twitch: 'KeyKagimura',
		nico: '',
		twitter: 'i/likes',
	},
	{
		pk: 125,
		name: '後頭部',
		twitch: 'kotobu417',
		nico: 'co2337287',
		twitter: 'ko10bu',
	},
	{pk: 126, name: '紺空', twitch: '', nico: 'co392367', twitter: 'konkuu'},
	{
		pk: 127,
		name: '佐々崎',
		twitch: '',
		nico: 'co2966950',
		twitter: 'sasazaki_t',
	},
	{
		pk: 128,
		name: '桜んぼ / Sakura',
		twitch: 'sakura_nbo',
		nico: 'co2045100',
		twitter: 'SKRSKFBK',
	},
	{
		pk: 129,
		name: '山下モズク',
		twitch: 'yama_mozu',
		nico: 'co3235618',
		twitter: 'Yama_Mozuku',
	},
	{
		pk: 130,
		name: '山成倉者',
		twitch: 'yamanarukuramono',
		nico: 'co3556995',
		twitter: 'yamanarukuramon',
	},
	{
		pk: 131,
		name: '死体',
		twitch: 'sitai1130',
		nico: 'co1417991',
		twitter: 'shitai_',
	},
	{
		pk: 132,
		name: '七瀬',
		twitch: 'nanaseseri',
		nico: '',
		twitter: 'nanaseseri',
	},
	{
		pk: 133,
		name: '照り焼きちきん',
		twitch: 'teriyakidori',
		nico: '',
		twitter: 'teriyakidori',
	},
	{pk: 134, name: '針金', twitch: '', nico: '', twitter: 'honwakawire'},
	{
		pk: 135,
		name: '水猫/aquacats',
		twitch: 'aquacats123',
		nico: '',
		twitter: 'aqua_cats',
	},
	{
		pk: 136,
		name: '青にいと',
		twitch: 'aoneet0721',
		nico: 'co1287117',
		twitter: 'aoneeet',
	},
	{
		pk: 137,
		name: '青色',
		twitch: '',
		nico: 'co1679655',
		twitter: 'aoiro_kabby',
	},
	{pk: 138, name: '爽', twitch: '', nico: 'co2952137', twitter: 'soumjpk'},
	{
		pk: 139,
		name: '泥酔',
		twitch: 'deisui25',
		nico: 'co2303822',
		twitter: 'deisuideisui',
	},
	{
		pk: 140,
		name: '楠木鳥夜(くすのきえぬ)',
		twitch: 'enu405969',
		nico: '47631882',
		twitter: 'enu405969',
	},
	{pk: 141, name: '燃え殻', twitch: '', nico: '', twitter: 'Dorianbooks'},
	{
		pk: 142,
		name: '龍咲ゆーみ',
		twitch: 'ryuuzakiyumi',
		nico: 'co2557010',
		twitter: 'yumi417246',
	},
	{
		pk: 143,
		name: '緑SM64',
		twitch: '',
		nico: 'co1593232',
		twitter: 'MidoriSM64',
	},
];
