/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
  horaroId?: string;
  animation?: {
    runnersInfoInterval?: number;
    sponsorInterval?: number;
  };
  twitter?: {
    targetWords: string[];
    maxTweets?: number;
    consumerKey: string;
    consumerSecret: string;
    accessTokenKey: string;
    accessTokenSecret: string;
  };
  twitch: {
    targetChannel: string;
    titleTemplate: string;
  };
}
