/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Configschema {
  horaroId?: string;
  runnerSpreadsheetId?: string;
  twitter: {
    targetWords: string[];
    maxTweets: number;
    consumerKey: string;
    consumerSecret: string;
  };
  twitch: {
    targetChannel: string;
    titleTemplate: string;
  };
}
