/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Schedule = {
	pk?: number;
	index: number;
	scheduled?: number;
	title?: string;
	engTitle?: string;
	category?: string;
	hardware?: string;
	duration?: string;
	runners?: {
		name?: string;
		twitch?: string;
		nico?: string;
		twitter?: string;
	}[];
	commentators?: {
		name?: string;
		twitch?: string;
		nico?: string;
		twitter?: string;
	}[];
}[];
