/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type GameList = {
  title?: string;
  engTitle?: string;
  runner?: string;
  commentator?: string;
  category?: string;
  hardware?: string;
  pk?: number;
  runnerPkAry?: number[];
  commentatorPkAry?: number[];
  duration?: string;
}[];
