/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Twitter {
  userObject?: {
    [k: string]: any;
  } | null;
  accessToken: string | null;
  accessTokenSecret: string | null;
  [k: string]: any;
}
